version: "3"
services:
  mongo:
    image: mongo:${SOFTWARE_VERSION_TAG}
    restart: always
    dns:
      - 8.8.8.8
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "Cluster0"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./data:/data/db
      - ./auth/key:/auth/key
    ports:
      - "17271:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "172.17.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://admin:${ADMIN_PASSWORD}@mongo:27017/
    depends_on:
      - mongo
      - mongosetup

  mongosetup:
    image: mongo:${SOFTWARE_VERSION_TAG}
    depends_on:
      - mongo
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: ["bash", "/scripts/mongo_setup.sh"]

  pritunl:
    image: docker.io/pritunl/pritunl-zero
    restart: always
    ports:
      - "172.17.0.1:4867:80"
      # - "443:443"
    environment:
      - "MONGO_URI=mongodb://admin:${ADMIN_PASSWORD}@${DOMAIN}:27710?authMechanism=SCRAM-SHA-1&authSource=admin"
      - NODE_ID=${NODE_ID}
    depends_on:
      - mongo-express
