version: "3.3"
services:
  pritunl:
    image: ghcr.io/jippi/docker-pritunl:${SOFTWARE_VERSION_TAG}
    restart: always
    privileged: true
    ports:
      - 172.17.0.1:4767:80
      - 172.17.0.1:4867:443
      - 1194:1194
      - 1194:1194/udp
    volumes:
      - "./data/mongodb:/var/lib/mongodb"
      - /root/.acme.sh/vm.elestio.app/fullchain.cer:/var/lib/pritunl/pritunl.crt
      - /root/.acme.sh/vm.elestio.app/vm.elestio.app.key:/var/lib/pritunl/pritunl.key
